---
apiVersion: v1
kind: Service
metadata:
  name: my-rabbit

spec:
  selector:
    app: my-rabbit

  ports:
    - name: http
      port: 15672
      nodePort: 31672 
    - name: endpoint
      port: 5672
      nodePort: 30672
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  selector:
    app: frontend

  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: trackorder

spec:
  selector:
    app: trackorder

  ports:
    - name: http
      port: 8081
      nodePort: 30081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8082
      nodePort: 30082
  type: NodePort
